### ISSUE TITLE
conflitto fra stili

### ISSUE THREAD

**Issue by diegolamonica** [diegolamonica/EUCookieLaw3-themes#2]
Aperta da @uroboroprogetti - da [Issue #2 in EUCookieLaw3 ](https://github.com/diegolamonica/EUCookieLaw3/issues/2)

Ciao e grazie ancora per il tuo prezioso lavoro;
ho purtroppo un problema con lo stile del banner; se nel codice includo le library di Bootstrap e JQuery il Banner viene visualizzato correttamente ma il tema del mio sito risulta leggermente alterato (dimensione dei font, rientri dei testi etc). Se invece non includo le library il banner non perde soltanto lo stile grafico ma anche la posizione, non risultando più fluttuante sopra la pagina ma fissato a fondo pagina sotto il footer. 

(n.b. fino a ieri l'avevo impostato con quest'ultima configurazione perché volevo mostrartelo, oggi invece ho cambiato con la configurazione che include le library e va in conflitto col CSS del mio tema, perché quel banner fissato sotto il footer era quasi invisibile)

**Comment by uroboroprogetti** [comment]
p.s. dopo aver installato la minor version ho notato un'altra cosa (non so se fosse presente anche prima): la prima riga del codice generato dal configuratore nel caso in cui NON includo le library ma solo uno dei temi predefiniti, cioè <link rel="stylesheet" href="https://diegolamonica.info/tools/eucookielaw/themes/bootstrap-like.css"> 
non viene salvata nel backend quando incollo il codice, è come se si "autocancellasse", e la cosa si verifica anche se cerco di inserire la riga a mano riscrivendola interamente...e si autocancella anche da questo commento (pensavo fosse un problema di browser ma ho fatto più prove, è la riga che inizia con "link rel="stylesheet etc)

**Comment by diegolamonica** [comment]
@uroboroprogetti ti prego di non riportare in questo repository problemi di funzionamento legati al [plugin per WordPress](https://github.com/diegolamonica/EUCookieLaw3-wp/). Eventuali problemi sul plugin devono essere [segnalati nel repository predisposto allo scopo](https://github.com/diegolamonica/EUCookieLaw3-wp/issues/), altrimenti altri utenti che cercano una risposta al problema non sono in grado di trovarla. 
In questa issue si sta discutendo del problema legato alle regole del CSS Darky-Miky.

**Comment by diegolamonica** [comment]
@uroboroprogetti sembra che tu non abbia indicato lo stile da utilizzare.
